export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_FOUND: "NOT_FOUND",
  ADAPTER_CONTRACT_VIOLATION: "ADAPTER_CONTRACT_VIOLATION",
  EXECUTION_CONVERGENCE_FAILED: "EXECUTION_CONVERGENCE_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
