export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_FOUND: "NOT_FOUND",
  ADAPTER_CONTRACT_VIOLATION: "ADAPTER_CONTRACT_VIOLATION",
  EXECUTION_CONVERGENCE_FAILED: "EXECUTION_CONVERGENCE_FAILED",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_INVALID_INPUT: "TOOL_INVALID_INPUT",
  TOOL_EXECUTION_FAILED: "TOOL_EXECUTION_FAILED",
  PLAN_VALIDATION_FAILED: "PLAN_VALIDATION_FAILED",
  PLAN_CANONICALIZATION_FAILED: "PLAN_CANONICALIZATION_FAILED",
  PLAN_EXCEEDS_MAX_STEPS: "PLAN_EXCEEDS_MAX_STEPS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
